/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_mcres_luckyfish_angustifolia_licenseclient_plugin_classloader_EncryptedClassLoader */

#ifndef _Included_com_mcres_luckyfish_angustifolia_licenseclient_plugin_classloader_EncryptedClassLoader
#define _Included_com_mcres_luckyfish_angustifolia_licenseclient_plugin_classloader_EncryptedClassLoader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_mcres_luckyfish_angustifolia_licenseclient_plugin_classloader_EncryptedClassLoader
 * Method:    analyzeClass
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_mcres_luckyfish_angustifolia_licenseclient_plugin_classloader_EncryptedClassLoader_analyzeClass
  (JNIEnv *, jclass, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
